version: '3.8'
services:
  pact-broker:
    image: pactfoundation/pact-broker
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_DATABASE_ADAPTER: "sqlite"

  product-api:
    build: ./product-api
    ports:
      - "8081:8081"