name: Pact Full CI Workflow

on:
  push:
    branches: [ main ]

jobs:
  pact-contract-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Start Pact Broker and Provider using Docker Compose
        run: |
          docker compose up -d
          echo "Waiting for Pact Broker..."
          until nc -z localhost 9292; do sleep 2; done
          echo "Waiting for Product API..."
          until nc -z localhost 8081; do sleep 2; done
          echo "Services are up and running!"

      # ---------- CONSUMER ----------
      - name: Install Consumer Dependencies
        working-directory: ./product-web-app
        run: npm ci

      - name: Run Consumer Pact Tests
        working-directory: ./product-web-app
        run: npm test

      - name: Publish Pacts to Broker
        working-directory: ./product-web-app
        run: |
          npx pact-broker publish pacts \
            --consumer-app-version=${{ github.sha }} \
            --broker-base-url=http://localhost:9292
        env:
          PACT_BROKER_BASE_URL: http://localhost:9292

      # ---------- PROVIDER ----------
      - name: Install Provider Dependencies
        working-directory: ./product-api
        run: npm ci

      - name: Run Provider Verification (and publish results)
        working-directory: ./product-api
        run: |
          npm test
        env:
          PACT_BROKER_URL: http://localhost:9292
          API_BASE_URL: http://localhost:8081
          PROVIDER_VERSION: ${{ github.sha }}
          CI: true

      # ---------- DEPLOY CHECK ----------
      - name: Pact Can I Deploy Check
        run: |
          npx @pact-foundation/pact-cli pact-broker can-i-deploy \
            --pacticipant ProductWebApp \
            --version ${{ github.sha }} \
            --to-environment production \
            --broker-base-url=http://localhost:9292
